language: go

go:
  - 1.3

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-go
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-go

install:
  - sudo wget -NO /usr/local/bin/src https://github.com/sourcegraph/srclib/releases/download/v0.0.12/src
  - sudo chmod +x /usr/local/bin/src
  - src toolchain add sourcegraph.com/sourcegraph/srclib-go
  - go get -d -v ./... && go build -v ./...
  # for tests
  - go get code.google.com/p/go.net/ipv6 code.google.com/p/go.tools/go/types
  - make

# TODO(sqs): add `go test`
script:
  - src test -m program
